language: python
# python:
#   - "3.11-dev"


install:
  - pip install -r requirements.txt

script:
- black --check .
- flake8 --max-line-length=150 .
- coverage run manage.py test


after_scripts:
- coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: AKIA6ODU6VDB5AVA4BGZ
  secret_access_key:
    secure: pqSaryBm5yZ8ImyGT2D8x5BVrgrrmNJaNfJtAbaCsxl0h39rv6rY42btSdvuSe9FMC+nYxraicPPxcjL43qcG5QdqHkwtDs1uKIgc1t9I1FWy1gQS8YRmO/mHB+H6vO7IimQ0ErktVAY8ilH+tT4RdpuEDDYvc7nodIRu1W66DVXovOYaMQy5QLUF4hWRzN9+kYrSQ0A9Sn/6DXVEqCpDPlGEdOMbNYbjZq00D47qmFU4XlQzJxUypMNUVX+//TM/9E/3izbmxAaAArg+LtKzk/ngw46Gn47Prqa6oAocuWGg7Rx5AhLgQX16a3GgGORyUOLq/m/CF2CI6wAbkiARfdm6yHZEjkjboXZHve1A/AvgASEkE6iQG8ouMr3ayIfcDD928zIDVC87Kh+EO/X75dFjqszyZFBF0Brl7wPkQ+qdXHDiAlPO5zq+OCGheWmv6bFTQIoS6RtwNA418Pc/hqNG7b5e+U6zL/4V/MdgkSzQLsIEudNnhx6B5dFE8rXBiu5wQsJZo7apDwiQbGqAScvA6sCprRoBW+MsreoPvP2jdVWpUCe8SMg5JVHUin/yejR194Fx++FxACInhrQnId8ETI8XrfnFAAH7hPWtJ9uEbUJF8O9ElvXXfBOyjG/aYtRABs3KmpgdFuO8s9n3F3DMWfX2C+7ATL8J0W6Xhw=
  region: us-west-2
  app: django-app
  env: Django-app-env
  bucket_name: elasticbeanstalk-us-west-2-992382724291
  on:
    repo: shreyas2499/swe1-app
    branch: main
  skip_cleanup: 'true'