language: python
# python:
#   - "3.11-dev"


install:
  - pip install -r requirements.txt

script:
- black --check .
- flake8 --max-line-length=150 .
- coverage run manage.py test


after_scripts:
- coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: AKIA6ODU6VDBZRVRV7HS
  secret_access_key:
    secure: ZyvbIL2GzMoq33+2E3y8+kMgkNLbALba2Qk2tWBv8nd1w1ENGwiBPEPPMn+ugEkv1/WjO1a5LsrFITHIkrcdaBz4MZ4NmFCaY2hNSdV6FA8sdNqo4rThl39lUYownRHaT9GZ+kU4nBrBAZGKbJo/ktxm9k0FltvnwUiPKTej6M/zyteeKunY6vzU4UO8REiIq8wwKvcfpqvLyVyhHEL/Zfoc6AqhZrzGrEO9F7xduzf9uJWUWt7f7D/oqobdUA7yhHDdUQrMHRecJSk/qGpzwt3e1GVW2pW5epHQm7BTXOzYY6NWdUn0OazSUqlDpqjYAm7Dg44LFn5y7uBjfUkb+1g+1D5Nispdb4TQp3Pg3AZblagFVOLUkQc6JPpiS01uyoUUxyGiXpjSKrj9VaWlqImCvWZYD1s3swh2GadyFmRLgqYJ0DTn+dVIdOavK8X/eiGGZpU+wF1VIXrcc+1UxaYPbe2eLPiYb5yYoufBrqbNgrIkkctOS2SVw5eeGWncRHaq2nnvSuDIAxFWcgUZyvePfgq/qn/yMnKagnSiKd/CqIUP3byFrlB045SOn6I9FVsQKs3HbsK/es3LiFgQudilwoWaMVdyD/QVE6/v1SenqnwLmQDCiSGg1pzs6MGNNS4gPfORjXAOgYmbo4yuXLd7uNxF76VsCAAByOz415g=
  region: us-west-2
  app: django-app
  env: Django-app-env
  bucket_name: elasticbeanstalk-us-west-2-992382724291
  on:
    repo: shreyas2499/swe1-app
    branch: main
  skip_cleanup: 'true'